### ISSUE TITLE
what version should i use for PixelmonSTSForge-1.1.7.jar

### ISSUE THREAD

**Issue by Kiriao** [landonjw/GooeyLibs#3]
PixelmonSTSForge-1.1.7.jar said that it require GooeyLibs but i can't seem to find GooeyLibs 1.0.6.jar version cause i tried v2.0.0 it crashed

**Comment by landonjw** [comment]
GooeyLibs 2.0.0 has major, API breaking changes. To get a jar of GooeyLibs 1.0.6 you can go to my discord (https://discord.gg/bvrpudqK) and get it from the GooeyLibs change-log channel.
